/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Errores;
import Controller.FileScanner;
import Controller.LexicAnalyzer;
import Controller.Token;
import Controller.Ut;
import java.awt.Color;
import java.io.File;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Element;
import javax.swing.text.Highlighter;

/**
 *
 * @author Hp EliteDesk
 */
public class index extends javax.swing.JFrame {
    JTextArea lineNumbers;
    
    DefaultHighlighter hl;
    Highlighter.HighlightPainter painter;
    
    int counter = 1;
    Color par, inpar;
    LexicAnalyzer la;
    int showMeFirst;
    
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        par = new Color(250, 207, 199);
        inpar = new Color(241, 150, 163);
        createLines();
    }
    
    private void createLines(){
        lineNumbers = new JTextArea("1");
        
        hl = (DefaultHighlighter) taBase.getHighlighter();
        taBase.setHighlighter(hl);
        hl.setDrawsLayeredHighlights(false);
        
        lineNumbers.setBackground(inpar);
        lineNumbers.setEditable(false);
        taBase.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                lineNumbers.setText(getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                lineNumbers.setText(getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                lineNumbers.setText(getText());
            }

            private String getText(){
                int caretPosition = taBase.getDocument().getLength();
                Element root = taBase.getDocument().getDefaultRootElement();
                String text = "1"+System.getProperty("line.separator");
                for (int i = 0; i < root.getElementIndex(caretPosition); i++) {
                    if((i+1)%2 ==0)
                        painter = (new DefaultHighlighter.DefaultHighlightPainter(par));
                    else
                        painter = (new DefaultHighlighter.DefaultHighlightPainter(inpar));
                    try{
                    taBase.getHighlighter().addHighlight(taBase.getLineStartOffset(i), taBase.getLineEndOffset(i), painter);
                    }catch(BadLocationException ble)
                    {
                        ble.printStackTrace();
                    }
                    text+= (i+2) + System.getProperty("line.separator");
                }
                return text;
            }
        });
        jspKodigo.setRowHeaderView(lineNumbers);
    }
    
    private void colorLines(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        container = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        jspKodigo = new javax.swing.JScrollPane();
        taBase = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblErrors = new javax.swing.JTable();
        pnlRight = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cmbLineas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblIdentificadores = new javax.swing.JLabel();
        lblPalabras = new javax.swing.JLabel();
        lblPalabrasNumeros = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblEnteros = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCaracteres = new javax.swing.JLabel();
        lblEqadsa = new javax.swing.JLabel();
        lblDecimal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblExponencial = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblMatematicos = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblMonogamo = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblLogicos = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblRelacionales = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblDesplazamiento = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lblPuntuacion = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblAgrupacion = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblAsignacion = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lblComentarios = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lblErrores = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblTodos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTokens = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        fc.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fc.setSelectedFile(new java.io.File("C:\\Program Files\\NetBeans 8.2\\AntonioLopez 19-03-18.xlsx"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(0, 204, 204));

        pnlLeft.setBackground(new java.awt.Color(241, 150, 163));
        pnlLeft.setAutoscrolls(true);

        jspKodigo.setBackground(new java.awt.Color(241, 150, 163));

        taBase.setBackground(new java.awt.Color(241, 150, 163));
        taBase.setColumns(20);
        taBase.setRows(5);
        jspKodigo.setViewportView(taBase);

        jScrollPane1.setBackground(new java.awt.Color(241, 150, 163));
        jScrollPane1.setBorder(null);

        tblErrors.setBackground(new java.awt.Color(241, 150, 163));
        tblErrors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Descripción", "Lexema", "Tipo de Error", "Línea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblErrors.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblErrors);
        if (tblErrors.getColumnModel().getColumnCount() > 0) {
            tblErrors.getColumnModel().getColumn(0).setResizable(false);
            tblErrors.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblErrors.getColumnModel().getColumn(1).setPreferredWidth(140);
            tblErrors.getColumnModel().getColumn(3).setResizable(false);
            tblErrors.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
            .addComponent(jspKodigo)
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addComponent(jspKodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pnlRight.setBackground(new java.awt.Color(0, 204, 204));
        pnlRight.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setBackground(new java.awt.Color(141, 209, 209));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(85, 221, 221));
        jPanel1.setPreferredSize(new java.awt.Dimension(385, 30));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(85, 221, 221));
        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTADORES");
        jPanel1.add(jLabel1);

        jPanel3.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(94, 154, 154));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(85, 221, 221));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel5.setPreferredSize(new java.awt.Dimension(385, 20));

        cmbLineas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cmbLineas.setEnabled(false);
        cmbLineas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLineasItemStateChanged(evt);
            }
        });
        cmbLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLineasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Línea:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 313, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbLineas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)))
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(85, 221, 221));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Identificadores: ");

        lblIdentificadores.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblIdentificadores.setForeground(new java.awt.Color(255, 255, 255));
        lblIdentificadores.setText("0");

        lblPalabras.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPalabras.setForeground(new java.awt.Color(255, 255, 255));
        lblPalabras.setText("Palabras Reservadas");

        lblPalabrasNumeros.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblPalabrasNumeros.setForeground(new java.awt.Color(255, 255, 255));
        lblPalabrasNumeros.setText("0");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Constantes");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enteros:");

        lblEnteros.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblEnteros.setForeground(new java.awt.Color(255, 255, 255));
        lblEnteros.setText("0");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Texto");

        lblTexto.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setText("0");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Carácteres: ");

        lblCaracteres.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblCaracteres.setForeground(new java.awt.Color(255, 255, 255));
        lblCaracteres.setText("0");

        lblEqadsa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblEqadsa.setForeground(new java.awt.Color(255, 255, 255));
        lblEqadsa.setText("Decimal: ");

        lblDecimal.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDecimal.setForeground(new java.awt.Color(255, 255, 255));
        lblDecimal.setText("0");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Exponencial:");

        lblExponencial.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblExponencial.setForeground(new java.awt.Color(255, 255, 255));
        lblExponencial.setText("0");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Operadores");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Matemáticos:");

        lblMatematicos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblMatematicos.setForeground(new java.awt.Color(255, 255, 255));
        lblMatematicos.setText("0");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Monógamo:");

        lblMonogamo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblMonogamo.setForeground(new java.awt.Color(255, 255, 255));
        lblMonogamo.setText("0");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Lógicos:");

        lblLogicos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblLogicos.setForeground(new java.awt.Color(255, 255, 255));
        lblLogicos.setText("0");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Relacionales:");

        lblRelacionales.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblRelacionales.setForeground(new java.awt.Color(255, 255, 255));
        lblRelacionales.setText("0");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Desplazamiento:");

        lblDesplazamiento.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDesplazamiento.setForeground(new java.awt.Color(255, 255, 255));
        lblDesplazamiento.setText("0");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Signos");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Puntuación:");

        lblPuntuacion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblPuntuacion.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntuacion.setText("0");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Agrupación:");

        lblAgrupacion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblAgrupacion.setForeground(new java.awt.Color(255, 255, 255));
        lblAgrupacion.setText("0");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Asignación:");

        lblAsignacion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblAsignacion.setForeground(new java.awt.Color(255, 255, 255));
        lblAsignacion.setText("0");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Comentarios:");

        lblComentarios.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblComentarios.setForeground(new java.awt.Color(255, 255, 255));
        lblComentarios.setText("0");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Errores: ");

        lblErrores.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblErrores.setForeground(new java.awt.Color(255, 255, 255));
        lblErrores.setText("0");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Total:");

        lblTodos.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTodos.setForeground(new java.awt.Color(255, 255, 255));
        lblTodos.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblEqadsa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCaracteres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblExponencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel36)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEnteros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblPalabras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPalabrasNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIdentificadores, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRelacionales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMatematicos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel18)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblLogicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel29)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblMonogamo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDesplazamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAgrupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblIdentificadores)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPalabras)
                    .addComponent(lblPalabrasNumeros)
                    .addComponent(jLabel19)
                    .addComponent(lblMatematicos)
                    .addComponent(jLabel20)
                    .addComponent(lblTodos))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(lblMonogamo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lblLogicos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lblRelacionales))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(lblDesplazamiento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(lblPuntuacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(lblAgrupacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(lblAsignacion)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblEnteros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblTexto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblCaracteres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEqadsa)
                            .addComponent(lblDecimal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lblExponencial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(lblComentarios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(lblErrores))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        pnlRight.add(jPanel3);

        jScrollPane2.setBackground(new java.awt.Color(85, 221, 221));
        jScrollPane2.setBorder(null);

        tblTokens.setBackground(new java.awt.Color(85, 221, 221));
        tblTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Lexema", "Línea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTokens.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblTokens);

        pnlRight.add(jScrollPane2);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton2.setText("Leer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setText("Compilar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FileScanner.leerArchivo(taBase, container);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        la = new LexicAnalyzer(taBase, this);
        la.stringAnalyzer();
        LinkedList lista1 = la.getTokenList();
        LinkedList lista2 = la.getErrorList();
        LinkedList lista3 = la.getVariableList();
        LinkedList lista4 = la.getContador();
        LinkedList lista5 = la.getAsignaciones();
        LinkedList lista6 = la.getContadorSemantica1();
        LinkedList lista7 = la.getLineaAsignaciones();
        LinkedList lista8 = la.getValoresSemantica();
        
        DefaultTableModel dtmTokens = (DefaultTableModel) tblTokens.getModel();
        dtmTokens.setRowCount(0);
        try{
            for (int i = 0; i < lista1.size(); i++){
                Token t = (Token) lista1.get(i);
                if(t.getNumero() != -2)
                    dtmTokens.addRow(((Token) lista1.get(i)).returnObject());
            }
        }catch(Exception e){}
        
        DefaultTableModel dtmErrors = (DefaultTableModel) tblErrors.getModel();
        dtmErrors.setRowCount(0);
        try{
            for (int i = 0; i < lista2.size(); i++)
                dtmErrors.addRow(((Errores)lista2.get(i)).returnObject());
        }catch(Exception e){
        }
        setNumbers();
        loadLineNumbers();
        setErrorLines();
        
        int returnVal = fc.showSaveDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                Ut.generateExcel(file, lista1, lista2, la.getLineNumbers(), la.getCounters(), lista3, lista4, lista6, lista5, lista7, lista8);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLineasActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLineasActionPerformed

    private void cmbLineasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLineasItemStateChanged
        if(cmbLineas.getSelectedIndex() == 0)
            setNumbers();
        else
            setNumbersByLine(cmbLineas.getSelectedIndex()+1);
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLineasItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }
    
    private void setNumbers(){
        LinkedList<Token> ll = la.getTokenList();
        LinkedList<Errores> listaErrores = la.getErrorList();
        lblIdentificadores.setText(""+ Ut.countTokenType(ll, -1));
        lblComentarios.setText(""+Ut.countTokenType(ll, -2));
        lblEnteros.setText(""+Ut.countTokenType(ll, -3));
        lblDecimal.setText(""+Ut.countTokenType(ll, -4));
        lblExponencial.setText(""+Ut.countTokenType(ll, -5));
        lblCaracteres.setText(""+Ut.countTokenType(ll, -6));
        lblTexto.setText(""+Ut.countTokenType(ll, -7));
        lblMatematicos.setText(""+Ut.getMatematicos(ll));
        lblMonogamo.setText(""+Ut.getMonogamos(ll));
        lblLogicos.setText(""+Ut.getLogicos(ll));
        lblRelacionales.setText(""+Ut.getRelacionales(ll));
        lblDesplazamiento.setText(""+Ut.getDesplazamiento(ll));
        lblPuntuacion.setText(""+Ut.getPuntuacion(ll));
        lblAgrupacion.setText(""+Ut.getAgrupacion(ll));
        lblAsignacion.setText(""+Ut.getAsignacion(ll));
        lblPalabrasNumeros.setText(""+Ut.getPalabrasReservadas(ll));
        lblErrores.setText(""+Ut.countError(listaErrores));
        lblTodos.setText(""+Ut.getAll(ll, listaErrores));
    }
    
    private void setNumbersByLine(int i){
        LinkedList<Token> ll = la.getTokenList();
        LinkedList<Errores> listaErrores = la.getErrorList();
        lblIdentificadores.setText(""+ Ut.countTokenTypeLine(ll, -1, i));
        lblComentarios.setText(""+Ut.countTokenTypeLine(ll, -2, i));
        lblEnteros.setText(""+Ut.countTokenTypeLine(ll, -3, i));
        lblDecimal.setText(""+Ut.countTokenTypeLine(ll, -4, i));
        lblExponencial.setText(""+Ut.countTokenTypeLine(ll, -5, i));
        lblCaracteres.setText(""+Ut.countTokenTypeLine(ll, -6, i));
        lblTexto.setText(""+Ut.countTokenTypeLine(ll, -7, i));
        lblMatematicos.setText(""+Ut.getMatematicosLinea(ll, i));
        lblMonogamo.setText(""+Ut.getMonogamosLinea(ll, i));
        lblLogicos.setText(""+Ut.getLogicosLinea(ll, i));
        lblRelacionales.setText(""+Ut.getRelacionalesLinea(ll, i));
        lblDesplazamiento.setText(""+Ut.getDesplazamientoLinea(ll, i));
        lblPuntuacion.setText(""+Ut.getPuntuacionLinea(ll, i));
        lblAgrupacion.setText(""+Ut.getAgrupacionLinea(ll, i));
        lblAsignacion.setText(""+Ut.getAsignacionLinea(ll, i));
        lblPalabrasNumeros.setText(""+Ut.getPalabrasReservadasByLine(ll, i));
        lblErrores.setText(""+Ut.countErrorLine(listaErrores, i));
        lblTodos.setText(""+Ut.getAllByLine(ll, listaErrores, i));
    }
    
    private void loadLineNumbers(){
        cmbLineas.setEnabled(true);
        cmbLineas.removeAllItems();
        cmbLineas.addItem("All");
        for (int i = 0; i < la.getLineNumbers(); i++) 
            cmbLineas.addItem(""+(i+1));
    }
    
    private void setErrorLines(){
        LinkedList<Errores> listaErrores = la.getErrorList();
        for (int i = 0; i < listaErrores.size(); i++) {
            try {
                if(listaErrores.get(i).getTipoError().equals("Léxico"))
                    painter = (new DefaultHighlighter.DefaultHighlightPainter(new Color(255, 53, 53)));
                else if(listaErrores.get(i).getTipoError().equals("Ambito"))
                    painter = (new DefaultHighlighter.DefaultHighlightPainter(new Color(172, 255, 48)));
                else
                    painter = (new DefaultHighlighter.DefaultHighlightPainter(new Color(33, 152, 161)));
                taBase.getHighlighter().addHighlight(taBase.getLineStartOffset((listaErrores.get(i).getLinea()-1)), taBase.getLineEndOffset((listaErrores.get(i).getLinea()-1)), painter);
            } catch (BadLocationException ex) {
                Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbLineas;
    private javax.swing.JPanel container;
    private javax.swing.JFileChooser fc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jspKodigo;
    private javax.swing.JLabel lblAgrupacion;
    private javax.swing.JLabel lblAsignacion;
    private javax.swing.JLabel lblCaracteres;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblDecimal;
    private javax.swing.JLabel lblDesplazamiento;
    private javax.swing.JLabel lblEnteros;
    private javax.swing.JLabel lblEqadsa;
    private javax.swing.JLabel lblErrores;
    private javax.swing.JLabel lblExponencial;
    private javax.swing.JLabel lblIdentificadores;
    private javax.swing.JLabel lblLogicos;
    private javax.swing.JLabel lblMatematicos;
    private javax.swing.JLabel lblMonogamo;
    private javax.swing.JLabel lblPalabras;
    private javax.swing.JLabel lblPalabrasNumeros;
    private javax.swing.JLabel lblPuntuacion;
    private javax.swing.JLabel lblRelacionales;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTodos;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JTextArea taBase;
    private javax.swing.JTable tblErrors;
    private javax.swing.JTable tblTokens;
    // End of variables declaration//GEN-END:variables
}
